# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_tutorial/infrastructure/grpc/proto/user_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_tutorial/infrastructure/grpc/proto/user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:grpc_tutorial/infrastructure/grpc/proto/user_service.proto\x12\x0cuser_service\"C\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"G\n\x12\x43reateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0fGetUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\"3\n\x10ListUsersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"E\n\x11ListUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user_service.User\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xf4\x01\n\x0bUserService\x12O\n\nCreateUser\x12\x1f.user_service.CreateUserRequest\x1a .user_service.CreateUserResponse\x12\x46\n\x07GetUser\x12\x1c.user_service.GetUserRequest\x1a\x1d.user_service.GetUserResponse\x12L\n\tListUsers\x12\x1e.user_service.ListUsersRequest\x1a\x1f.user_service.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_tutorial.infrastructure.grpc.proto.user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=76
  _globals['_USER']._serialized_end=143
  _globals['_CREATEUSERREQUEST']._serialized_start=145
  _globals['_CREATEUSERREQUEST']._serialized_end=193
  _globals['_CREATEUSERRESPONSE']._serialized_start=195
  _globals['_CREATEUSERRESPONSE']._serialized_end=266
  _globals['_GETUSERREQUEST']._serialized_start=268
  _globals['_GETUSERREQUEST']._serialized_end=296
  _globals['_GETUSERRESPONSE']._serialized_start=298
  _globals['_GETUSERRESPONSE']._serialized_end=349
  _globals['_LISTUSERSREQUEST']._serialized_start=351
  _globals['_LISTUSERSREQUEST']._serialized_end=402
  _globals['_LISTUSERSRESPONSE']._serialized_start=404
  _globals['_LISTUSERSRESPONSE']._serialized_end=473
  _globals['_USERSERVICE']._serialized_start=476
  _globals['_USERSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
